export default {
  RU: {
    labels: {
      syncCloud: 'СИНХРОНИЗАЦИЯ С ОБЛАКОМ',
      addProfile: 'Добавить профиль',
      config: 'Параметры',
      logs: 'Логи',
      usersProfile: 'Профили пользователей',
      search: 'Поиск',
      profileDetails: 'Детали профиля',
      profileInfo: 'Информация о профиле',
      personalInfo: 'Личная информация',
      enabled: 'Активен',
      disabled: 'Неактивен',
      edit: 'Редактировать',
      remove: 'Удалить',
      removing: 'Удаление',
      saving: 'Сохранение',
      save: 'Сохранить',
      cancel: 'Отмена',
      lastEdited: 'Изменен',
      success: 'Успех!',
      add: 'Добавить',
      adding: 'Добавление',
      login: 'Логин',
      params: 'Параметры',
      reset: 'Сбросить пользователей',
    },
  },
  EN: {
    labels: {
      syncCloud: 'SYNC WITH CLOUD',
      addProfile: 'Add Profile',
      config: 'Config',
      logs: 'Logs',
      usersProfile: 'User Profiles',
      search: 'Search',
      profileDetails: 'Profile Details',
      profileInfo: 'Customer Information',
      personalInfo: 'Personal Information',
      enabled: 'Enabled',
      disabled: 'Disabled',
      edit: 'Edit',
      remove: 'Remove',
      removing: 'Remove',
      saving: 'Saving',
      save: 'Save',
      cancel: 'Cancel',
      lastEdited: 'Last Updated by',
      success: 'Success!',
      add: 'Add',
      adding: 'Add',
      login: 'Login',
      params: 'Params',
      reset: 'Reset',
      first_name: 'First Name',
      last_name: 'Last Name',
      gender: 'Gender',
      phone: 'Phone',
      addUsers: 'Add 10 users',
      removeUsers: 'Remove all users',
    },
  },
};
